import { notFound } from 'next/navigation';
const content:Record<string,{title:string;copy:string;items:string[]}>= {
 landlords:{title:'Electrical management for landlords.',copy:'Keep properties compliant and resolve electrical work without maintaining a separate contractor relationship for every address.',items:['EICR and remedial tracking','Property electrical history','Tenant-facing booking support','Emergency escalation','Certificate records']},
 agents:{title:'One electrical workflow for every managed property.',copy:'Give property managers one route for jobs, compliance, tenant access and portfolio reporting.',items:['Multi-property job logging','EICR visibility','Central certificates','Service-level tracking','Consolidated reporting']},
 facilities:{title:'Electrical service built for facilities teams.',copy:'Coordinate reactive, planned and compliance work across sites through one managed operating layer.',items:['SLA routing','Multi-site dispatch','Planned maintenance','Escalation management','Spend visibility']},
 enterprise:{title:'National electrical coverage with one accountable relationship.',copy:'Built for organisations that need consistent service standards across a distributed estate.',items:['National-account controls','Role-based users','Portfolio reporting','Emergency response','Commercial service agreements']},
 'public-sector':{title:'Electrical services for housing and public estates.',copy:'A procurement-ready pathway for organisations that need evidence, consistency and accountable service delivery.',items:['Compliance evidence','Audit trail','Accessible reporting','Service standards','Supplier assurance']}
};
export default async function BusinessSegmentPage({params}:{params:Promise<{segment:string}>}){const {segment}=await params;const c=content[segment];if(!c)notFound();return <section className='page narrow'><span className='eyebrow'>For businesses</span><h1>{c.title}</h1><p className='lede'>{c.copy}</p><div className='panel'><h2>Designed around</h2><ul>{c.items.map(x=><li key={x}>{x}</li>)}</ul><button className='button primary'>Talk to the business team</button></div></section>}
