'use client';

import { FormEvent,useState } from 'react';

export function OpportunityForm({organisationId,supervisors}:{organisationId:string;supervisors:Array<{id:string;name:string}>}){
  const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const f=new FormData(event.currentTarget);const body={organisationId,opportunityType:String(f.get('opportunityType')),title:String(f.get('title')),postcode:String(f.get('postcode')),places:Number(f.get('places')||1),minimumStage:String(f.get('minimumStage')||'')||undefined,desiredSkills:String(f.get('desiredSkills')||'').split(',').map(x=>x.trim()).filter(Boolean),daysAvailable:String(f.get('daysAvailable')||'').split(',').map(x=>x.trim()).filter(Boolean),paid:f.get('paid')==='on',compensationNotes:String(f.get('compensationNotes')||''),supervisorEngineerId:String(f.get('supervisorEngineerId')||'')||undefined,startsOn:String(f.get('startsOn')||'')||undefined,endsOn:String(f.get('endsOn')||'')||undefined};const r=await fetch('/api/provider/opportunities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));setMessage(d.message||d.error||'Unable to create opportunity.');setBusy(false);if(r.ok){event.currentTarget.reset();setTimeout(()=>window.location.reload(),700)}}
  return <form className='form-card' onSubmit={submit}><h2>Offer a learner opportunity</h2><p className='form-help'>Trainee placements must have an independently eligible supervisor before activation. This does not replace formal apprenticeship/training-provider requirements.</p><div className='form-grid'><label>Type<select name='opportunityType' defaultValue='placement'><option value='work_experience'>Work experience</option><option value='placement'>Placement</option><option value='apprenticeship'>Apprenticeship</option><option value='trainee_job'>Trainee job</option><option value='qualified_job'>Qualified job</option><option value='mentoring'>Mentoring</option></select></label><label>Title<input name='title' required placeholder='Domestic electrical placement'/></label><label>Postcode<input name='postcode' required/></label><label>Places<input type='number' name='places' min='1' max='100' defaultValue='1'/></label><label>Minimum stage<select name='minimumStage' defaultValue=''><option value=''>Any suitable stage</option><option value='exploring'>Exploring</option><option value='learner'>Learner</option><option value='placement'>Placement-ready</option><option value='apprentice'>Apprentice</option><option value='qualified'>Qualified</option></select></label><label>Supervisor<select name='supervisorEngineerId' required><option value=''>Select eligible supervisor</option>{supervisors.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Start date<input type='date' name='startsOn'/></label><label>End date<input type='date' name='endsOn'/></label></div><label>Skills / work areas<input name='desiredSkills' placeholder='fault-finding,eicr,domestic'/></label><label>Days available<input name='daysAvailable' placeholder='Tuesday,Wednesday,Thursday'/></label><label className='check-row'><input type='checkbox' name='paid'/> Paid opportunity</label><label>Pay / compensation details<input name='compensationNotes' placeholder='Enter the actual arrangement; do not imply funding.'/></label><button className='button primary' disabled={busy||supervisors.length===0}>{busy?'Publishing…':'Publish opportunity'}</button>{supervisors.length===0&&<p className='form-message'>Verify an independently eligible supervisor before offering placements.</p>}{message&&<p className='form-message'>{message}</p>}</form>;
}
