import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';

const schema=z.object({applicantName:z.string().trim().min(2).max(160),email:z.string().trim().toLowerCase().email(),qualificationSummary:z.string().trim().min(5).max(2000),desiredStructure:z.enum(['undecided','sole_trader','limited_company']).default('undecided'),companyNameChoice:z.string().trim().max(160).optional(),explicitFilingConsent:z.boolean().default(false)}).superRefine((v,ctx)=>{if(v.explicitFilingConsent&&v.desiredStructure==='undecided')ctx.addIssue({code:'custom',path:['desiredStructure'],message:'Choose a structure before giving filing consent.'});});

export async function POST(request:Request){
  const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the business setup details.'},{status:400});
  const supabase=await getUserSupabase();const {data:{user}}=supabase?await supabase.auth.getUser():{data:{user:null}};
  try{const admin=getAdminSupabase();let linkedUser=user?.id||null;if(!linkedUser){const {data:profile}=await admin.from('profiles').select('id').ilike('email',parsed.data.email).maybeSingle();linkedUser=profile?.id||null;}const status=parsed.data.desiredStructure==='undecided'?'eligibility_review':parsed.data.explicitFilingConsent?'awaiting_approval':'structure_selected';const {data:row,error}=await admin.from('business_setup_cases').insert({user_id:linkedUser,email:parsed.data.email,applicant_name:parsed.data.applicantName,qualification_summary:parsed.data.qualificationSummary,desired_structure:parsed.data.desiredStructure,status,explicit_filing_consent:parsed.data.explicitFilingConsent,company_name_choice:parsed.data.companyNameChoice||null,hmrc_setup_status:'not_started',insurance_status:'not_started',banking_status:'not_started',payments_status:'not_started'}).select('id,status').single();if(error||!row)return NextResponse.json({error:'Unable to start business setup.',detail:error?.message},{status:500});await admin.from('audit_events').insert({actor_user_id:linkedUser,event_type:'business_setup.started',entity_type:'business_setup_case',entity_id:row.id,metadata:{desiredStructure:parsed.data.desiredStructure,explicitFilingConsent:parsed.data.explicitFilingConsent}});return NextResponse.json({id:row.id,status:row.status,message:parsed.data.explicitFilingConsent?'Setup case created with your filing consent recorded. No incorporation or HMRC filing is submitted until the exact filing is prepared and approved.':'Setup case created. You can choose or confirm the legal structure before any filing is prepared.'},{status:201});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to start business setup.'},{status:500});}
}
