'use client';

import { FormEvent,useEffect,useState } from 'react';

type Connection={id:string;provider:string;external_calendar_id:string|null;sync_direction:string;status:string;last_synced_at:string|null;last_error:string|null};

export function CalendarConnectionManager({engineerId}:{engineerId:string}){
  const [connections,setConnections]=useState<Connection[]>([]);const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  async function load(){const res=await fetch(`/api/provider/calendar-connections?engineerId=${encodeURIComponent(engineerId)}`,{cache:'no-store'});const data=await res.json();if(res.ok)setConnections(data.connections||[])}
  useEffect(()=>{void load()},[engineerId]);
  async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const form=new FormData(e.currentTarget);const externalCalendarId=String(form.get('url')||'').trim();try{const res=await fetch('/api/provider/calendar-connections',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({engineerId,provider:'ical',externalCalendarId,syncDirection:'read_busy'})});const data=await res.json();setMessage(res.ok?'Calendar feed saved. The secure pull worker will import busy periods without copying event titles or attendee details.':data.error||'Unable to save calendar feed.');if(res.ok){e.currentTarget.reset();await load()}}finally{setBusy(false)}}
  async function revoke(id:string){setBusy(true);try{const res=await fetch(`/api/provider/calendar-connections?engineerId=${encodeURIComponent(engineerId)}&connectionId=${encodeURIComponent(id)}`,{method:'DELETE'});const data=await res.json();setMessage(res.ok?'Calendar connection revoked and imported busy blocks removed.':data.error||'Unable to revoke calendar.');if(res.ok)await load()}finally{setBusy(false)}}
  return <section className='portal-card'><h3>External calendar conflicts</h3><p className='form-help'>Optional read-only iCalendar feeds can block out busy periods in dispatch. Feed URLs must use public HTTPS; private/local addresses are rejected by the pull worker.</p><form className='form-grid' onSubmit={add}><label>Private iCalendar feed URL<input name='url' type='url' required placeholder='https://…/calendar.ics'/></label><button className='button' disabled={busy}>{busy?'Saving…':'Connect iCalendar feed'}</button></form>{connections.map(c=><article className='record-row' key={c.id}><div><strong>{c.provider.toUpperCase()} · {c.status}</strong><span>{c.last_synced_at?`last synced ${new Date(c.last_synced_at).toLocaleString('en-GB')}`:'not synced yet'}{c.last_error?` · ${c.last_error}`:''}</span></div><button className='button' type='button' disabled={busy} onClick={()=>void revoke(c.id)}>Revoke</button></article>)}{message&&<p className='note'>{message}</p>}<p className='form-help'>Google and Microsoft OAuth adapters remain optional future integrations; the platform scheduling engine does not depend on them.</p></section>
}
