import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';

const schema=z.object({engineerId:z.string().uuid(),provider:z.enum(['google','microsoft','ical']),externalCalendarId:z.string().trim().max(500).optional(),credentialReference:z.string().trim().max(500).optional(),syncDirection:z.enum(['read_busy','two_way']).default('read_busy')});
async function access(engineerId:string){const db=await getUserSupabase();if(!db)return null;const {data:{user}}=await db.auth.getUser();if(!user)return null;const {data:engineer}=await db.from('engineers').select('id,user_id,organisation_id').eq('id',engineerId).maybeSingle();if(!engineer)return null;const {data:member}=await db.from('organisation_members').select('role').eq('organisation_id',engineer.organisation_id).eq('user_id',user.id).maybeSingle();const own=engineer.user_id===user.id;const manage=Boolean(member&&['owner','admin','manager'].includes(member.role));return{db,user,engineer,allowed:own||manage}}
export async function GET(request:Request){const engineerId=new URL(request.url).searchParams.get('engineerId');if(!engineerId)return NextResponse.json({error:'engineerId required.'},{status:400});const ctx=await access(engineerId);if(!ctx)return NextResponse.json({error:'Sign in required.'},{status:401});if(!ctx.allowed)return NextResponse.json({error:'Access denied.'},{status:403});const {data,error}=await ctx.db.from('provider_calendar_connections').select('id,provider,external_calendar_id,sync_direction,status,last_synced_at,last_error,created_at').eq('engineer_id',engineerId).order('created_at',{ascending:false});if(error)return NextResponse.json({error:'Unable to load calendar connections.'},{status:500});return NextResponse.json({connections:data||[]})}
export async function POST(request:Request){const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the calendar connection.'},{status:400});const ctx=await access(parsed.data.engineerId);if(!ctx)return NextResponse.json({error:'Sign in required.'},{status:401});if(!ctx.allowed)return NextResponse.json({error:'Access denied.'},{status:403});try{const admin=getAdminSupabase();if(parsed.data.provider!=='ical'&&!parsed.data.credentialReference)return NextResponse.json({error:'OAuth credential reference is required for Google or Microsoft. Raw access tokens must not be stored here.'},{status:400});const {data,error}=await admin.from('provider_calendar_connections').upsert({engineer_id:parsed.data.engineerId,provider:parsed.data.provider,external_calendar_id:parsed.data.externalCalendarId||null,credential_reference:parsed.data.credentialReference||null,sync_direction:parsed.data.syncDirection,status:'pending',updated_at:new Date().toISOString()},{onConflict:'engineer_id,provider,external_calendar_id'}).select('id,provider,status,sync_direction').single();if(error)return NextResponse.json({error:'Unable to save calendar connection.',detail:error.message},{status:500});await admin.from('audit_events').insert({actor_user_id:ctx.user.id,event_type:'calendar.connection_configured',entity_type:'engineer',entity_id:parsed.data.engineerId,metadata:{connectionId:data.id,provider:parsed.data.provider,syncDirection:parsed.data.syncDirection}});return NextResponse.json({connection:data,message:'Connection configured. External synchronisation remains inactive until the provider OAuth/sync worker confirms access.'},{status:201});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to save calendar connection.'},{status:500})}}
export async function DELETE(request:Request){const url=new URL(request.url);const engineerId=url.searchParams.get('engineerId');const connectionId=url.searchParams.get('connectionId');if(!engineerId||!connectionId)return NextResponse.json({error:'engineerId and connectionId required.'},{status:400});const ctx=await access(engineerId);if(!ctx)return NextResponse.json({error:'Sign in required.'},{status:401});if(!ctx.allowed)return NextResponse.json({error:'Access denied.'},{status:403});try{const admin=getAdminSupabase();await admin.from('provider_calendar_connections').update({status:'revoked',credential_reference:null,updated_at:new Date().toISOString()}).eq('id',connectionId).eq('engineer_id',engineerId);await admin.from('external_calendar_busy_blocks').delete().eq('connection_id',connectionId);await admin.from('audit_events').insert({actor_user_id:ctx.user.id,event_type:'calendar.connection_revoked',entity_type:'engineer',entity_id:engineerId,metadata:{connectionId}});return NextResponse.json({ok:true});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to revoke calendar connection.'},{status:500})}}
