import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';

const schema=z.object({organisationId:z.string().uuid(),businessStructure:z.enum(['company','sole_trader','partnership','other']),accountingBasis:z.enum(['accrual','cash']),vatRegistered:z.boolean(),vatNumber:z.string().trim().max(40).optional(),vatScheme:z.enum(['standard','cash_accounting','flat_rate','annual_accounting','not_registered']),financialYearEndMonth:z.coerce.number().int().min(1).max(12),financialYearEndDay:z.coerce.number().int().min(1).max(31),mtdVatEnabled:z.boolean().default(false),mtdIncomeTaxEnabled:z.boolean().default(false)}).superRefine((v,ctx)=>{if(v.vatRegistered&&!v.vatNumber)ctx.addIssue({code:'custom',path:['vatNumber'],message:'VAT number is required for a VAT-registered business.'});if(!v.vatRegistered&&v.mtdVatEnabled)ctx.addIssue({code:'custom',path:['mtdVatEnabled'],message:'MTD VAT cannot be enabled for a non-VAT-registered business.'});});

export async function POST(request:Request){
  const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the accounting settings.'},{status:400});
  const supabase=await getUserSupabase();if(!supabase)return NextResponse.json({error:'Sign in required.'},{status:401});const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});
  const {data:membership}=await supabase.from('organisation_members').select('role').eq('organisation_id',parsed.data.organisationId).eq('user_id',user.id).maybeSingle();if(!membership||!['owner','admin','manager'].includes(membership.role))return NextResponse.json({error:'Business owner or manager access required.'},{status:403});
  try{const admin=getAdminSupabase();const {error}=await admin.from('accounting_profiles').upsert({organisation_id:parsed.data.organisationId,business_structure:parsed.data.businessStructure,accounting_basis:parsed.data.accountingBasis,vat_registered:parsed.data.vatRegistered,vat_number:parsed.data.vatRegistered?parsed.data.vatNumber:null,vat_scheme:parsed.data.vatRegistered?parsed.data.vatScheme:'not_registered',financial_year_end_month:parsed.data.financialYearEndMonth,financial_year_end_day:parsed.data.financialYearEndDay,mtd_vat_enabled:parsed.data.mtdVatEnabled,mtd_income_tax_enabled:parsed.data.mtdIncomeTaxEnabled,updated_at:new Date().toISOString()},{onConflict:'organisation_id'});if(error)return NextResponse.json({error:'Unable to save accounting settings.',detail:error.message},{status:500});await admin.from('audit_events').insert({actor_user_id:user.id,event_type:'finance.accounting_profile_saved',entity_type:'organisation',entity_id:parsed.data.organisationId,metadata:{businessStructure:parsed.data.businessStructure,vatRegistered:parsed.data.vatRegistered,vatScheme:parsed.data.vatScheme,mtdVatEnabled:parsed.data.mtdVatEnabled,mtdIncomeTaxEnabled:parsed.data.mtdIncomeTaxEnabled}});return NextResponse.json({message:'Accounting settings saved. Tax submissions remain disabled until the relevant HMRC integration is explicitly configured.'});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to save accounting settings.'},{status:500});}
}
