import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';

const schema=z.object({organisationId:z.string().uuid(),engineerId:z.string().uuid().optional(),jobId:z.string().uuid().optional(),travelledOn:z.string().date(),purpose:z.string().trim().min(2).max(300),distanceMiles:z.coerce.number().positive().max(5000),startPostcode:z.string().trim().max(12).optional(),endPostcode:z.string().trim().max(12).optional(),source:z.enum(['manual','job_route','import']).default('manual')});

export async function POST(request:Request){
  const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the mileage details.'},{status:400});
  const supabase=await getUserSupabase();if(!supabase)return NextResponse.json({error:'Sign in required.'},{status:401});const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});
  const {data:membership}=await supabase.from('organisation_members').select('role').eq('organisation_id',parsed.data.organisationId).eq('user_id',user.id).maybeSingle();if(!membership)return NextResponse.json({error:'Business membership required.'},{status:403});
  try{const admin=getAdminSupabase();if(parsed.data.engineerId){const {data:engineer}=await admin.from('engineers').select('organisation_id,user_id').eq('id',parsed.data.engineerId).maybeSingle();if(!engineer||engineer.organisation_id!==parsed.data.organisationId)return NextResponse.json({error:'Engineer does not belong to this business.'},{status:400});if(!['owner','admin','manager','dispatcher'].includes(membership.role)&&engineer.user_id!==user.id)return NextResponse.json({error:'You can only record your own mileage.'},{status:403});}const {data:row,error}=await admin.from('mileage_records').insert({organisation_id:parsed.data.organisationId,engineer_id:parsed.data.engineerId??null,job_id:parsed.data.jobId??null,travelled_on:parsed.data.travelledOn,purpose:parsed.data.purpose,distance_miles:parsed.data.distanceMiles,source:parsed.data.source,start_postcode:parsed.data.startPostcode||null,end_postcode:parsed.data.endPostcode||null,created_by:user.id}).select('id').single();if(error||!row)return NextResponse.json({error:'Unable to record mileage.',detail:error?.message},{status:500});return NextResponse.json({id:row.id,message:'Mileage record saved. Tax treatment is not inferred automatically; your accounting profile or adviser determines any claim.'},{status:201});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to record mileage.'},{status:500});}
}
