import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';

const schema=z.object({educationOrganisationId:z.string().uuid(),displayName:z.string().trim().min(2).max(160),email:z.string().trim().toLowerCase().email().optional(),postcode:z.string().trim().min(3).max(12),ageBand:z.enum(['under_16','16_17','18_plus']),travelRadiusKm:z.coerce.number().positive().max(250).default(15),hasOwnTransport:z.boolean().default(false),currentStage:z.enum(['exploring','learner','placement','apprentice','qualified','verified_provider','mentor']).default('learner'),qualificationSummary:z.string().trim().max(1000).optional(),desiredSkills:z.array(z.string().trim().min(2).max(120)).max(50).default([]),availabilitySummary:z.string().trim().max(500).optional(),placementMatchingConsent:z.boolean().default(false),employerSharingConsent:z.boolean().default(false),evidenceRecordingConsent:z.boolean().default(false),guardianApproval:z.boolean().default(false),guardianName:z.string().trim().max(160).optional(),guardianRelationship:z.string().trim().max(80).optional()});

export async function POST(request:Request){
  const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the learner details.'},{status:400});
  const supabase=await getUserSupabase();if(!supabase)return NextResponse.json({error:'Sign in required.'},{status:401});const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});
  const {data:membership}=await supabase.from('organisation_members').select('role').eq('organisation_id',parsed.data.educationOrganisationId).eq('user_id',user.id).maybeSingle();if(!membership)return NextResponse.json({error:'Education-partner membership required.'},{status:403});
  try{const admin=getAdminSupabase();const {data:org}=await admin.from('organisations').select('kind').eq('id',parsed.data.educationOrganisationId).maybeSingle();if(!org||org.kind!=='education_provider')return NextResponse.json({error:'Education partner not found.'},{status:404});let linkedUser:string|null=null;if(parsed.data.email){const {data:profile}=await admin.from('profiles').select('id').ilike('email',parsed.data.email).maybeSingle();linkedUser=profile?.id||null;}const {data:learner,error}=await admin.from('learners').insert({user_id:linkedUser,education_organisation_id:parsed.data.educationOrganisationId,display_name:parsed.data.displayName,email:parsed.data.email||null,postcode:parsed.data.postcode.toUpperCase(),age_band:parsed.data.ageBand,travel_radius_km:parsed.data.travelRadiusKm,has_own_transport:parsed.data.hasOwnTransport,current_stage:parsed.data.currentStage,qualification_summary:parsed.data.qualificationSummary||null,desired_skills:parsed.data.desiredSkills,availability_summary:parsed.data.availabilitySummary||null,status:'active'}).select('id').single();if(error||!learner)return NextResponse.json({error:'Unable to create learner record.',detail:error?.message},{status:500});const under18=parsed.data.ageBand!=='18_plus';const guardianOk=!under18||parsed.data.guardianApproval;const consentRows=[{learner_id:learner.id,consent_type:'placement_matching',granted:parsed.data.placementMatchingConsent&&guardianOk,captured_by:user.id},{learner_id:learner.id,consent_type:'employer_sharing',granted:parsed.data.employerSharingConsent&&guardianOk,captured_by:user.id},{learner_id:learner.id,consent_type:'evidence_recording',granted:parsed.data.evidenceRecordingConsent&&guardianOk,captured_by:user.id},{learner_id:learner.id,consent_type:'guardian_approval',granted:guardianOk,granted_by_name:parsed.data.guardianName||null,granted_by_relationship:parsed.data.guardianRelationship||null,captured_by:user.id}];await admin.from('learner_consents').insert(consentRows);await admin.from('audit_events').insert({actor_user_id:user.id,event_type:'academy.learner_created',entity_type:'learner',entity_id:learner.id,metadata:{educationOrganisationId:parsed.data.educationOrganisationId,ageBand:parsed.data.ageBand,placementMatchingEnabled:parsed.data.placementMatchingConsent&&guardianOk}});return NextResponse.json({id:learner.id,matchingEnabled:parsed.data.placementMatchingConsent&&guardianOk,message:under18&&!parsed.data.guardianApproval?'Learner added. Placement matching remains off until guardian approval is recorded.':'Learner added to the Academy workforce pipeline.'},{status:201});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to create learner.'},{status:500});}
}
