'use client';

import { FormEvent,useState } from 'react';

export function LearnerForm({organisationId}:{organisationId:string}){
  const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);const[ageBand,setAgeBand]=useState<'under_16'|'16_17'|'18_plus'>('18_plus');
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const f=new FormData(event.currentTarget);const body={educationOrganisationId:organisationId,displayName:String(f.get('displayName')),email:String(f.get('email')||'')||undefined,postcode:String(f.get('postcode')),ageBand,travelRadiusKm:Number(f.get('travelRadiusKm')||15),hasOwnTransport:f.get('hasOwnTransport')==='on',currentStage:String(f.get('currentStage')),qualificationSummary:String(f.get('qualificationSummary')||''),desiredSkills:String(f.get('desiredSkills')||'').split(',').map(x=>x.trim()).filter(Boolean),availabilitySummary:String(f.get('availabilitySummary')||''),placementMatchingConsent:f.get('placementMatchingConsent')==='on',employerSharingConsent:f.get('employerSharingConsent')==='on',evidenceRecordingConsent:f.get('evidenceRecordingConsent')==='on',guardianApproval:f.get('guardianApproval')==='on',guardianName:String(f.get('guardianName')||''),guardianRelationship:String(f.get('guardianRelationship')||'')};const r=await fetch('/api/academy/learners',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));setMessage(d.message||d.error||'Unable to add learner.');setBusy(false);if(r.ok){event.currentTarget.reset();setAgeBand('18_plus');setTimeout(()=>window.location.reload(),700)}}
  return <form className='form-card' onSubmit={submit}><h2>Add learner</h2><p className='form-help'>Placement matching only uses records where the required sharing/matching consent is current. Under-18 learners also require guardian approval before employer matching.</p><div className='form-grid'><label>Name<input name='displayName' required/></label><label>Email<input type='email' name='email'/></label><label>Postcode<input name='postcode' required/></label><label>Age band<select value={ageBand} onChange={e=>setAgeBand(e.target.value as typeof ageBand)}><option value='18_plus'>18+</option><option value='16_17'>16–17</option><option value='under_16'>Under 16</option></select></label><label>Travel radius (km)<input type='number' name='travelRadiusKm' min='1' max='250' defaultValue='15'/></label><label>Stage<select name='currentStage' defaultValue='learner'><option value='exploring'>Exploring</option><option value='learner'>Learner</option><option value='placement'>Placement</option><option value='apprentice'>Apprentice</option><option value='qualified'>Qualified</option></select></label></div><label>Qualifications / current learning<textarea name='qualificationSummary'/></label><label>Skills they want to develop<input name='desiredSkills' placeholder='fault-finding, eicr, ev-charging'/></label><label>Availability<input name='availabilitySummary' placeholder='Tue–Thu, college Mon/Fri'/></label><label className='check-row'><input type='checkbox' name='hasOwnTransport'/> Has own transport</label><label className='check-row'><input type='checkbox' name='placementMatchingConsent'/> Consent to automated placement matching</label><label className='check-row'><input type='checkbox' name='employerSharingConsent'/> Consent to share necessary profile data with matched employers</label><label className='check-row'><input type='checkbox' name='evidenceRecordingConsent'/> Consent to supervised competency evidence recording</label>{ageBand!=='18_plus'&&<div className='form-grid'><label className='check-row'><input type='checkbox' name='guardianApproval'/> Guardian approval recorded</label><label>Guardian name<input name='guardianName'/></label><label>Relationship<input name='guardianRelationship'/></label></div>}<button className='button primary' disabled={busy}>{busy?'Adding…':'Add learner'}</button>{message&&<p className='form-message'>{message}</p>}</form>;
}

type ConsentType='placement_matching'|'employer_sharing'|'evidence_recording'|'guardian_approval';
const LABELS:Record<ConsentType,string>={placement_matching:'Placement matching',employer_sharing:'Employer sharing',evidence_recording:'Competency evidence',guardian_approval:'Guardian approval'};

export function ConsentControls({learnerId,ageBand,current}:{learnerId:string;ageBand:string;current:Partial<Record<ConsentType,boolean>>}){
  const[busy,setBusy]=useState<string|null>(null);const[message,setMessage]=useState('');
  async function update(consentType:ConsentType,action:'grant'|'withdraw'){
    let guardianName:string|undefined;
    let guardianRelationship:string|undefined;
    if(action==='grant'&&consentType==='guardian_approval'){
      guardianName=window.prompt('Guardian name')||undefined;
      if(!guardianName)return;
      guardianRelationship=window.prompt('Relationship to learner')||undefined;
    }
    setBusy(consentType);setMessage('');
    const r=await fetch(`/api/academy/learners/${learnerId}/consents`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({consentType,action,guardianName,guardianRelationship})});
    const d=await r.json().catch(()=>({}));setMessage(d.message||d.error||'Unable to update consent.');setBusy(null);if(r.ok)setTimeout(()=>window.location.reload(),500);
  }
  const types:ConsentType[]=ageBand==='18_plus'?['placement_matching','employer_sharing','evidence_recording']:['guardian_approval','placement_matching','employer_sharing','evidence_recording'];
  return <div className='consent-controls'>{types.map(type=>{const active=Boolean(current[type]);return <div className='consent-row' key={type}><span><strong>{LABELS[type]}</strong><small>{active?'Current':'Not current'}</small></span><button type='button' className='button' disabled={Boolean(busy)} onClick={()=>update(type,active?'withdraw':'grant')}>{busy===type?'Saving…':active?'Withdraw':'Grant'}</button></div>})}{message&&<p className='form-message'>{message}</p>}</div>;
}
