import { NextResponse } from 'next/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';
import { internalRequestAuthorised } from '@/lib/internal';

export async function POST(request:Request){
 if(!internalRequestAuthorised(request))return NextResponse.json({error:'Unauthorised.'},{status:401});
 try{const admin=getAdminSupabase();const now=Date.now();const {data:jobs,error}=await admin.from('jobs').select('id,business_organisation_id,corporate_sla_id,status,requested_start,arrived_at,work_started_at,completed_at,created_at,postcode').not('corporate_sla_id','is',null).not('status','in','("closed","cancelled")').limit(250);if(error)return NextResponse.json({error:'Unable to load SLA jobs.'},{status:500});const slaIds=[...new Set((jobs||[]).map(j=>j.corporate_sla_id).filter(Boolean))];const {data:slas}=slaIds.length?await admin.from('corporate_slas').select('id,name,response_target_minutes,attendance_target_minutes,resolution_target_minutes,escalation_policy').in('id',slaIds):{data:[]};const map=new Map((slas||[]).map(s=>[s.id,s]));const breaches:Array<Record<string,unknown>>=[];
 for(const job of jobs||[]){const sla=map.get(job.corporate_sla_id);if(!sla)continue;const reasons:string[]=[];if(job.requested_start&&sla.attendance_target_minutes&&!job.arrived_at){const due=new Date(job.requested_start).getTime()+Number(sla.attendance_target_minutes)*60_000;if(now>due)reasons.push(`attendance>${sla.attendance_target_minutes}m`)}if(job.work_started_at&&sla.resolution_target_minutes&&!job.completed_at){const due=new Date(job.work_started_at).getTime()+Number(sla.resolution_target_minutes)*60_000;if(now>due)reasons.push(`resolution>${sla.resolution_target_minutes}m`)}if(!reasons.length)continue;const evidence={slaId:sla.id,slaName:sla.name,reasons,postcode:job.postcode,requestedStart:job.requested_start,arrivedAt:job.arrived_at,workStartedAt:job.work_started_at};await admin.from('recovery_signals').upsert({job_id:job.id,signal_type:'sla_breach',severity:'high',evidence,status:'open'},{onConflict:'job_id,signal_type,status'});await admin.from('jobs').update({operational_risk_state:'sla_breach',updated_at:new Date().toISOString()}).eq('id',job.id);await admin.from('audit_events').insert({event_type:'corporate.sla_breach_detected',entity_type:'job',entity_id:job.id,metadata:evidence});const {data:profile}=job.business_organisation_id?await admin.from('corporate_billing_profiles').select('billing_email').eq('organisation_id',job.business_organisation_id).maybeSingle():{data:null};if(profile?.billing_email)await admin.rpc('queue_notification',{p_recipient_user_id:null,p_recipient_email:profile.billing_email,p_channel:'email',p_template_key:'corporate_sla_breach',p_payload:{jobId:job.id,slaName:sla.name,reasons,postcode:job.postcode},p_scheduled_at:new Date().toISOString()});breaches.push({jobId:job.id,sla:sla.name,reasons})}
 return NextResponse.json({checked:jobs?.length||0,breaches:breaches.length,results:breaches});
 }catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'SLA monitor failed.'},{status:500})}
}
