import { NextResponse } from 'next/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';
import { internalRequestAuthorised } from '@/lib/internal';

export async function POST(request:Request){
 if(!internalRequestAuthorised(request))return NextResponse.json({error:'Unauthorised.'},{status:401});
 try{const admin=getAdminSupabase();const since=new Date(Date.now()-30*86_400_000).toISOString();const {data:reviews,error}=await admin.from('reviews').select('id,job_id,provider_id,customer_user_id,rating,review,created_at,moderation_status').gte('created_at',since).in('moderation_status',['pending','published']).order('created_at',{ascending:false}).limit(500);if(error)return NextResponse.json({error:'Unable to load reviews.'},{status:500});const results:Array<Record<string,unknown>>=[];
 for(const r of reviews||[]){const signals:Array<{type:string;score:number;evidence:Record<string,unknown>}>=[];const text=String(r.review||'').trim();if(text.length>0&&text.length<20)signals.push({type:'very_short_text',score:.25,evidence:{characters:text.length}});if(Number(r.rating)===1||Number(r.rating)===5)signals.push({type:'rating_extreme',score:.08,evidence:{rating:r.rating}});const sameUser=(reviews||[]).filter(x=>x.customer_user_id===r.customer_user_id);if(sameUser.length>=5)signals.push({type:'high_review_velocity',score:Math.min(.75,.15*sameUser.length),evidence:{reviewsIn30Days:sameUser.length}});const duplicate=text.length>30?(reviews||[]).filter(x=>x.id!==r.id&&String(x.review||'').trim().toLowerCase()===text.toLowerCase()).length:0;if(duplicate)signals.push({type:'duplicate_review_text',score:.9,evidence:{duplicates:duplicate}});for(const s of signals)await admin.from('review_risk_signals').upsert({review_id:r.id,signal_type:s.type,score:s.score,evidence:s.evidence},{onConflict:'review_id,signal_type'});const risk=signals.length?Math.max(...signals.map(s=>s.score)):0;results.push({reviewId:r.id,risk,signals:signals.map(s=>s.type),action:risk>=.75?'manual_review':'normal_moderation'})}
 return NextResponse.json({processed:results.length,flagged:results.filter(r=>Number(r.risk)>=.75).length,results});
 }catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Review risk worker failed.'},{status:500})}
}
