import { NextResponse } from 'next/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';
import { internalRequestAuthorised } from '@/lib/internal';

const BATCH=100;
export async function POST(request:Request){if(!internalRequestAuthorised(request))return NextResponse.json({error:'Unauthorised.'},{status:401});try{const db=getAdminSupabase();const now=new Date();const results:Array<Record<string,unknown>>=[];
  const {data:eligible}=await db.from('jobs').select('id,matched_provider_id,provider_price_pence,settlement_status,completed_at,providers!inner(id,organisation_id)').in('settlement_status',['held','eligible']).not('matched_provider_id','is',null).gt('provider_price_pence',0).limit(BATCH);
  for(const job of eligible||[]){const provider=job.providers as unknown as {id:string;organisation_id:string};const {data:policies}=await db.from('provider_reserve_policies').select('id,reserve_bps,maximum_reserve_pence,release_after_days,minimum_job_pence,reason').eq('organisation_id',provider.organisation_id).eq('active',true).lte('minimum_job_pence',Number(job.provider_price_pence));const policy=(policies||[])[0];if(!policy)continue;let amount=Math.round(Number(job.provider_price_pence)*Number(policy.reserve_bps)/10000);if(policy.maximum_reserve_pence!=null)amount=Math.min(amount,Number(policy.maximum_reserve_pence));if(amount<=0)continue;const releaseAt=new Date((job.completed_at?new Date(job.completed_at):now).getTime()+Number(policy.release_after_days)*86400000).toISOString();const {data:hold,error}=await db.from('provider_reserve_holds').upsert({job_id:job.id,provider_id:provider.id,policy_id:policy.id,amount_pence:amount,status:'held',reason:policy.reason,release_at:releaseAt},{onConflict:'job_id,provider_id,policy_id'}).select('id,amount_pence').maybeSingle();if(!error&&hold){await db.from('jobs').update({settlement_status:'held'}).eq('id',job.id).in('settlement_status',['eligible','held']);results.push({jobId:job.id,action:'hold',amountPence:hold.amount_pence})}}
  const {data:due}=await db.from('provider_reserve_holds').select('id,job_id,provider_id,amount_pence').eq('status','held').lte('release_at',now.toISOString()).limit(BATCH);for(const hold of due||[]){const {data:cases}=await db.from('job_cases').select('id').eq('job_id',hold.job_id).in('status',['open','pending']).limit(1);const {data:signals}=await db.from('recovery_signals').select('id').eq('job_id',hold.job_id).eq('status','open').limit(1);if((cases||[]).length||(signals||[]).length){results.push({jobId:hold.job_id,action:'release_blocked'});continue}await db.from('provider_reserve_holds').update({status:'released',released_at:now.toISOString()}).eq('id',hold.id).eq('status','held');await db.from('audit_events').insert({event_type:'provider_reserve.released',entity_type:'job',entity_id:hold.job_id,metadata:{holdId:hold.id,providerId:hold.provider_id,amountPence:hold.amount_pence}});results.push({jobId:hold.job_id,action:'released',amountPence:hold.amount_pence})}
  return NextResponse.json({processed:results.length,results});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Reserve worker failed.'},{status:500})}}
