'use client';
import { FormEvent,useMemo,useState } from 'react';

type Structure='undecided'|'sole_trader'|'limited_company';
type Answer='yes'|'no'|'unsure';
type Scenario={key:string;label:string;sole:string;limited:string;professional?:boolean};

const scenarios:Scenario[]=[
 {key:'admin',label:'I want the lightest possible administration while I establish demand.',sole:'Often points toward exploring sole-trader operation first.',limited:'A company adds statutory administration, so this factor alone does not favour incorporation.'},
 {key:'staff',label:'I expect to employ staff, bring in shareholders or build a larger organisation.',sole:'Possible, but ownership and investment options are less separated from you personally.',limited:'Often strengthens the case for exploring a company structure.'},
 {key:'separation',label:'Clear separation between personal and business assets/contracts matters to me.',sole:'You and the business are the same legal person.',limited:'A company is a separate legal entity, although personal guarantees or misconduct can still create personal exposure.',professional:true},
 {key:'sale',label:'I want the business to be easier to invest in, share or sell later.',sole:'A sole-trader business can be sold, but ownership is not represented by company shares.',limited:'Company shares can make future ownership/investment changes more structured.'},
 {key:'tax',label:'My main reason for choosing a structure is tax.',sole:'Tax outcomes depend on profit and individual circumstances.',limited:'Company/director/shareholder tax outcomes are more complex and should not be chosen from a generic calculator.',professional:true},
 {key:'contracts',label:'Important customers/frameworks may prefer contracting with a company.',sole:'Some buyers accept sole traders; others impose their own supplier requirements.',limited:'Can align with buyers that require or strongly prefer incorporated suppliers.'}
];

export function BusinessSetupWizard(){
 const [busy,setBusy]=useState(false);const [result,setResult]=useState('');const [structure,setStructure]=useState<Structure>('undecided');const [answers,setAnswers]=useState<Record<string,Answer>>({});
 const guidance=useMemo(()=>structure==='sole_trader'?['Simpler administration and no incorporation filing.','You and the business are not separate legal persons.','You still need appropriate tax, insurance and record-keeping setup.']:structure==='limited_company'?['A separate legal entity can support growth, staff and clearer separation.','Company administration and statutory filings are added responsibilities.','Director/shareholder/tax implications should be checked for your circumstances.']:['Choose based on how you expect to operate, risk, administration and growth—not because the platform pushes one structure.'],[structure]);
 const assessment=useMemo(()=>{
   let sole=0,limited=0,professional=false;
   for(const item of scenarios){const answer=answers[item.key];if(answer!=='yes')continue;if(item.key==='admin')sole+=2;else if(['staff','separation','sale','contracts'].includes(item.key))limited+=2;if(item.professional)professional=true;}
   if(!Object.keys(answers).length)return null;
   const direction=limited>=sole+2?'limited_company':sole>=limited+2?'sole_trader':'undecided';
   return{direction,professional,sole,limited};
 },[answers]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setResult('');const form=new FormData(e.currentTarget);const body={applicantName:String(form.get('name')||''),email:String(form.get('email')||''),qualificationSummary:String(form.get('qualification')||''),desiredStructure:structure,companyNameChoice:String(form.get('companyName')||'')||undefined,explicitFilingConsent:form.get('filingConsent')==='on',decisionContext:{answers,assessment}};const res=await fetch('/api/business-setup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await res.json();setResult(res.ok?`${data.message} Case ${data.id}.`:(data.error||'Unable to start setup.'));setBusy(false)}
 return <section className='portal-card'><h2>Build your launch route</h2><div className='chips'>{(['undecided','sole_trader','limited_company'] as Structure[]).map(v=><button key={v} type='button' className='button' onClick={()=>setStructure(v)}>{v==='undecided'?'Help me decide':v==='sole_trader'?'Sole trader':'Limited company'}</button>)}</div><ul>{guidance.map(x=><li key={x}>{x}</li>)}</ul><h3>Neutral structure check</h3><p className='note'>These questions highlight operational trade-offs only. They do not calculate personal tax or determine legal liability.</p><div className='form-grid'>{scenarios.map(item=><fieldset key={item.key}><legend>{item.label}</legend><div className='chips'>{(['yes','no','unsure'] as Answer[]).map(value=><button key={value} type='button' className='button' aria-pressed={answers[item.key]===value} onClick={()=>setAnswers(current=>({...current,[item.key]:value}))}>{value}</button>)}</div>{answers[item.key]==='yes'&&<p className='note'>Sole trader: {item.sole}<br/>Limited company: {item.limited}</p>}</fieldset>)}</div>{assessment&&<div className='portal-card'><strong>{assessment.direction==='limited_company'?'Your answers make a limited company worth exploring.':assessment.direction==='sole_trader'?'Your answers make sole-trader operation worth exploring.':'Your answers are mixed; neither structure is an obvious operational fit.'}</strong><p className='note'>This is decision support, not a recommendation. {assessment.professional?'Because your answers touch tax/liability consequences, obtain accountant or legal advice before relying on the structure choice.':'You can still choose either route after considering administration, contracts and future plans.'}</p><button type='button' className='button' onClick={()=>setStructure(assessment.direction)}>Use this as my working route</button></div>}<form onSubmit={submit} className='form-grid'><label>Name<input name='name' required minLength={2}/></label><label>Email<input name='email' type='email' required/></label><label>Qualification summary<textarea name='qualification' required minLength={5}/></label>{structure==='limited_company'&&<label>Preferred company name<input name='companyName'/></label>}<label><input name='filingConsent' type='checkbox'/> Record consent to prepare a filing for later explicit approval</label><button className='button primary' disabled={busy}>{busy?'Creating…':'Create setup case'}</button></form>{result&&<p className='note'>{result}</p>}</section>
}
