'use client';
import { FormEvent,useMemo,useState } from 'react';

type Structure='undecided'|'sole_trader'|'limited_company';

export function BusinessSetupWizard(){
 const [busy,setBusy]=useState(false);const [result,setResult]=useState('');const [structure,setStructure]=useState<Structure>('undecided');
 const guidance=useMemo(()=>structure==='sole_trader'?['Simpler administration and no incorporation filing.','You and the business are not separate legal persons.','You still need appropriate tax, insurance and record-keeping setup.']:structure==='limited_company'?['A separate legal entity can support growth, staff and clearer separation.','Company administration and statutory filings are added responsibilities.','Director/shareholder/tax implications should be checked for your circumstances.']:['Choose based on how you expect to operate, risk, administration and growth—not because the platform pushes one structure.'],[structure]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setResult('');const form=new FormData(e.currentTarget);const body={applicantName:String(form.get('name')||''),email:String(form.get('email')||''),qualificationSummary:String(form.get('qualification')||''),desiredStructure:structure,companyNameChoice:String(form.get('companyName')||'')||undefined,explicitFilingConsent:form.get('filingConsent')==='on'};const res=await fetch('/api/business-setup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await res.json();setResult(res.ok?`${data.message} Case ${data.id}.`:(data.error||'Unable to start setup.'));setBusy(false)}
 return <section className='portal-card'><h2>Build your launch route</h2><div className='chips'>{(['undecided','sole_trader','limited_company'] as Structure[]).map(v=><button key={v} type='button' className='button' onClick={()=>setStructure(v)}>{v==='undecided'?'Help me decide':v==='sole_trader'?'Sole trader':'Limited company'}</button>)}</div><ul>{guidance.map(x=><li key={x}>{x}</li>)}</ul><form onSubmit={submit} className='form-grid'><label>Name<input name='name' required minLength={2}/></label><label>Email<input name='email' type='email' required/></label><label>Qualification summary<textarea name='qualification' required minLength={5}/></label>{structure==='limited_company'&&<label>Preferred company name<input name='companyName'/></label>}<label><input name='filingConsent' type='checkbox'/> Record consent to prepare a filing for later explicit approval</label><button className='button primary' disabled={busy}>{busy?'Creating…':'Create setup case'}</button></form>{result&&<p className='note'>{result}</p>}</section>
}
