import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';

const updateSchema=z.object({caseId:z.string().uuid(),stepKey:z.string().trim().min(2).max(80),status:z.enum(['not_started','in_progress','waiting_approval','completed','blocked','not_applicable']),notes:z.string().trim().max(1000).optional(),evidence:z.record(z.string(),z.unknown()).optional()});
const defaultSteps=['structure','identity','companies_house','hmrc','insurance','banking','payments','pricing','coverage','compliance','finance_records'];

async function ownedCase(caseId:string,userId:string){const admin=getAdminSupabase();const {data}=await admin.from('business_setup_cases').select('id,user_id,desired_structure,status').eq('id',caseId).maybeSingle();return data?.user_id===userId?data:null}

export async function GET(request:Request){const db=await getUserSupabase();if(!db)return NextResponse.json({error:'Sign in required.'},{status:401});const {data:{user}}=await db.auth.getUser();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});const caseId=new URL(request.url).searchParams.get('caseId');if(!caseId)return NextResponse.json({error:'caseId required.'},{status:400});try{const row=await ownedCase(caseId,user.id);if(!row)return NextResponse.json({error:'Setup case not found.'},{status:404});const admin=getAdminSupabase();const {data:steps}=await admin.from('business_setup_steps').select('step_key,status,completed_at,evidence,notes,updated_at').eq('case_id',caseId).order('step_key');const existing=new Map((steps||[]).map(s=>[s.step_key,s]));const merged=defaultSteps.map(stepKey=>existing.get(stepKey)||{step_key:stepKey,status:'not_started',completed_at:null,evidence:{},notes:null});return NextResponse.json({case:row,steps:merged,completion:Math.round(merged.filter(s=>s.status==='completed'||s.status==='not_applicable').length/merged.length*100)});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to load setup progress.'},{status:500})}}

export async function POST(request:Request){const parsed=updateSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the setup step.'},{status:400});const db=await getUserSupabase();if(!db)return NextResponse.json({error:'Sign in required.'},{status:401});const {data:{user}}=await db.auth.getUser();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});try{const owned=await ownedCase(parsed.data.caseId,user.id);if(!owned)return NextResponse.json({error:'Setup case not found.'},{status:404});const admin=getAdminSupabase();const now=new Date().toISOString();const {data,error}=await admin.from('business_setup_steps').upsert({case_id:parsed.data.caseId,step_key:parsed.data.stepKey,status:parsed.data.status,notes:parsed.data.notes||null,evidence:parsed.data.evidence||{},completed_at:parsed.data.status==='completed'?now:null,updated_at:now},{onConflict:'case_id,step_key'}).select('step_key,status,completed_at').single();if(error)return NextResponse.json({error:'Unable to save setup step.',detail:error.message},{status:500});await admin.from('audit_events').insert({actor_user_id:user.id,event_type:'business_setup.step_updated',entity_type:'business_setup_case',entity_id:parsed.data.caseId,metadata:{stepKey:parsed.data.stepKey,status:parsed.data.status}});return NextResponse.json({step:data});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to save setup progress.'},{status:500})}}
