import Link from 'next/link';

const sections=[
 ['Provider verification','Business identity, qualification or competent-person evidence, public-liability insurance, service capability and expiry monitoring are checked before the network marks a business verified. Network verification is not statutory accreditation.'],
 ['Electrical safety','Descriptions suggesting an immediate electrical hazard are diverted from ordinary booking rather than remotely diagnosed. Trainees cannot be marked independently dispatchable, and competency expiry can remove unsupervised eligibility.'],
 ['Customer protection','Payment is separated from provider settlement. Completion, open cases, compliance and recovery checks can hold settlement. Approved recovery policies support refunds, rework and reassignment; ambiguous safety/legal cases remain exceptions.'],
 ['Payments & pricing','The electrician owns the underlying rate. The standard marketplace policy adds the customer service fee separately and shows provider price, platform fee and customer total rather than silently deducting a second commission.'],
 ['Privacy & location','Live engineer location is opt-in, active-session only and short-lived. Precise worker location is not exposed publicly. Customer coordinates are used only when supplied for dispatch/routing purposes.'],
 ['Security & access','Supabase RLS, server-side service credentials, signed Stripe webhooks, idempotent workers and role-aware portals provide technical separation. Service-only control tables remain inaccessible to ordinary client roles by default.'],
 ['Auditability','Provider status, moderation, payments, recovery, finance entries, reversals and autonomous actions generate auditable records. Financial corrections reverse or adjust prior entries rather than silently rewriting history.'],
 ['Responsible automation','Routine matching, expiry monitoring, reconciliation, notifications and recovery can run automatically. Uncertainty, safety, regulatory and legally consequential filing steps are designed to stop at an explicit approval or exception boundary.'],
 ['Complaints & recovery','Structured cases can represent complaints, disputes, rework, refunds and safety issues. No-show and overrun telemetry can create objective recovery signals and block settlement while the issue is resolved.'],
 ['Accessibility & resilience','The service is being built around clear status, readable disclosure, alternative contact/booking paths and failure-safe workers. Production readiness still requires live smoke tests of hosting, payments, routing, messaging and recovery.']
] as const;

export default function TrustPage(){return <section className='page'><span className='eyebrow'>National Electrician Hub trust centre</span><h1>Trust should be inspectable.</h1><p className='lede'>This page describes controls that exist in the platform and clearly separates them from external accreditation or guarantees we do not make.</p><div className='cards three'>{sections.map(([title,body])=><article key={title}><h2>{title}</h2><p>{body}</p></article>)}</div><section className='portal-card'><h2>Verify a network member</h2><p>Each approved provider can have a public verification record and live network badge. The badge reflects National Electrician Hub network status only.</p><div className='actions'><Link className='button primary' href='/electricians/verification'>How verification works</Link><Link className='button' href='/about'>About the operator</Link></div></section><section className='portal-card'><h2>Legal operator</h2><p><strong>National Electrician Hub</strong> and <strong>Raeburn Services</strong> are trading names of <strong>The Raeburn Holding Group Limited</strong>, registered in England and Wales, company number 17361231.</p></section></section>}
