import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';

const schema=z.object({organisationId:z.string().uuid(),opportunityType:z.enum(['work_experience','placement','apprenticeship','trainee_job','qualified_job','mentoring']),title:z.string().trim().min(3).max(200),postcode:z.string().trim().min(3).max(12),places:z.coerce.number().int().min(1).max(100).default(1),minimumStage:z.string().trim().max(80).optional(),desiredSkills:z.array(z.string().trim().min(2).max(120)).max(50).default([]),daysAvailable:z.array(z.string().trim().min(2).max(20)).max(14).default([]),paid:z.boolean().optional(),compensationNotes:z.string().trim().max(500).optional(),supervisorEngineerId:z.string().uuid().optional(),startsOn:z.string().date().optional(),endsOn:z.string().date().optional()}).refine(v=>!v.startsOn||!v.endsOn||v.endsOn>=v.startsOn,{path:['endsOn'],message:'End date must be on or after start date.'});

export async function POST(request:Request){
  const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the opportunity details.'},{status:400});
  const supabase=await getUserSupabase();if(!supabase)return NextResponse.json({error:'Sign in required.'},{status:401});const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});
  const {data:membership}=await supabase.from('organisation_members').select('role').eq('organisation_id',parsed.data.organisationId).eq('user_id',user.id).maybeSingle();if(!membership||!['owner','admin','manager'].includes(membership.role))return NextResponse.json({error:'Business owner or manager access required.'},{status:403});
  try{const admin=getAdminSupabase();const {data:provider}=await admin.from('providers').select('id,verification_state').eq('organisation_id',parsed.data.organisationId).maybeSingle();if(!provider||provider.verification_state!=='active')return NextResponse.json({error:'Only active verified provider businesses can offer learner opportunities.'},{status:403});if(parsed.data.supervisorEngineerId){const {data:supervisor}=await admin.from('engineers').select('organisation_id,can_work_unsupervised,status').eq('id',parsed.data.supervisorEngineerId).maybeSingle();if(!supervisor||supervisor.organisation_id!==parsed.data.organisationId||!supervisor.can_work_unsupervised||supervisor.status!=='active')return NextResponse.json({error:'Supervisor must be an active independently eligible engineer in this business.'},{status:400});}const {data:opportunity,error}=await admin.from('employer_opportunities').insert({provider_id:provider.id,opportunity_type:parsed.data.opportunityType,title:parsed.data.title,postcode:parsed.data.postcode.toUpperCase(),places:parsed.data.places,minimum_stage:parsed.data.minimumStage||null,desired_skills:parsed.data.desiredSkills,days_available:parsed.data.daysAvailable,paid:parsed.data.paid??null,compensation_notes:parsed.data.compensationNotes||null,supervisor_engineer_id:parsed.data.supervisorEngineerId||null,status:'open',starts_on:parsed.data.startsOn||null,ends_on:parsed.data.endsOn||null}).select('id').single();if(error||!opportunity)return NextResponse.json({error:'Unable to create opportunity.',detail:error?.message},{status:500});await admin.from('audit_events').insert({actor_user_id:user.id,event_type:'academy.employer_opportunity_created',entity_type:'employer_opportunity',entity_id:opportunity.id,metadata:{organisationId:parsed.data.organisationId,opportunityType:parsed.data.opportunityType,places:parsed.data.places}});return NextResponse.json({id:opportunity.id,message:'Opportunity is live for consented learner matching.'},{status:201});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to create opportunity.'},{status:500});}
}
