'use client';

import { FormEvent,useState } from 'react';
const poundsToPence=(v:FormDataEntryValue|null)=>Math.round(Number(v||0)*100);

export function AccountingProfileForm({organisationId,initial}:{organisationId:string;initial?:{business_structure?:string;accounting_basis?:string;vat_registered?:boolean;vat_number?:string|null;vat_scheme?:string;financial_year_end_month?:number;financial_year_end_day?:number;mtd_vat_enabled?:boolean;mtd_income_tax_enabled?:boolean}|null}){
  const[vatRegistered,setVatRegistered]=useState(Boolean(initial?.vat_registered));const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const f=new FormData(event.currentTarget);const body={organisationId,businessStructure:String(f.get('businessStructure')),accountingBasis:String(f.get('accountingBasis')),vatRegistered,vatNumber:String(f.get('vatNumber')||'')||undefined,vatScheme:vatRegistered?String(f.get('vatScheme')):'not_registered',financialYearEndMonth:Number(f.get('financialYearEndMonth')),financialYearEndDay:Number(f.get('financialYearEndDay')),mtdVatEnabled:vatRegistered&&f.get('mtdVatEnabled')==='on',mtdIncomeTaxEnabled:f.get('mtdIncomeTaxEnabled')==='on'};const r=await fetch('/api/provider/finance/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));setMessage(d.message||d.error||'Unable to save accounting settings.');setBusy(false);if(r.ok)setTimeout(()=>window.location.reload(),700)}
  return <form className='form-card' onSubmit={submit}><h2>Accounting & HMRC-ready settings</h2><p className='form-help'>These settings control digital records and VAT calculations. Enabling an MTD flag does not itself submit anything to HMRC.</p><div className='form-grid'><label>Business structure<select name='businessStructure' defaultValue={initial?.business_structure||'company'}><option value='company'>Limited company</option><option value='sole_trader'>Sole trader</option><option value='partnership'>Partnership</option><option value='other'>Other</option></select></label><label>Accounting basis<select name='accountingBasis' defaultValue={initial?.accounting_basis||'accrual'}><option value='accrual'>Accrual</option><option value='cash'>Cash</option></select></label><label>Year-end month<input name='financialYearEndMonth' type='number' min='1' max='12' defaultValue={initial?.financial_year_end_month||12}/></label><label>Year-end day<input name='financialYearEndDay' type='number' min='1' max='31' defaultValue={initial?.financial_year_end_day||31}/></label></div><label className='check-row'><input type='checkbox' checked={vatRegistered} onChange={e=>setVatRegistered(e.target.checked)}/> VAT registered</label>{vatRegistered&&<div className='form-grid'><label>VAT number<input name='vatNumber' required defaultValue={initial?.vat_number||''}/></label><label>VAT scheme<select name='vatScheme' defaultValue={initial?.vat_scheme||'standard'}><option value='standard'>Standard</option><option value='cash_accounting'>Cash accounting</option><option value='flat_rate'>Flat Rate Scheme</option><option value='annual_accounting'>Annual Accounting</option></select></label></div>}<label className='check-row'><input type='checkbox' name='mtdVatEnabled' defaultChecked={Boolean(initial?.mtd_vat_enabled)} disabled={!vatRegistered}/> Maintain MTD VAT digital records</label><label className='check-row'><input type='checkbox' name='mtdIncomeTaxEnabled' defaultChecked={Boolean(initial?.mtd_income_tax_enabled)}/> Maintain MTD Income Tax digital records where applicable</label><button className='button primary' disabled={busy}>{busy?'Saving…':'Save accounting settings'}</button>{message&&<p className='form-message'>{message}</p>}</form>;
}

export function ExpenseForm({organisationId}:{organisationId:string}){
  const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const f=new FormData(event.currentTarget);const body={organisationId,incurredOn:String(f.get('incurredOn')),category:String(f.get('category')),description:String(f.get('description')),supplierName:String(f.get('supplierName')||''),netPence:poundsToPence(f.get('net')),vatPence:poundsToPence(f.get('vat')),taxCode:String(f.get('taxCode')||'')||undefined};const r=await fetch('/api/provider/finance/expense',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));setMessage(d.message||d.error||'Unable to record expense.');setBusy(false);if(r.ok){event.currentTarget.reset();setTimeout(()=>window.location.reload(),700)}}
  return <form className='form-card' onSubmit={submit}><h2>Record expense</h2><div className='form-grid'><label>Date<input type='date' name='incurredOn' required/></label><label>Category<input name='category' required placeholder='Materials, travel, software…'/></label><label>Supplier<input name='supplierName'/></label><label>Net (£)<input type='number' name='net' min='0' step='0.01' required/></label><label>VAT (£)<input type='number' name='vat' min='0' step='0.01' defaultValue='0'/></label><label>Tax code<input name='taxCode' placeholder='Optional'/></label></div><label>Description<input name='description' required/></label><button className='button' disabled={busy}>{busy?'Recording…':'Record & post to ledger'}</button>{message&&<p className='form-message'>{message}</p>}</form>;
}

export function MileageForm({organisationId}:{organisationId:string}){
  const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const f=new FormData(event.currentTarget);const body={organisationId,travelledOn:String(f.get('travelledOn')),purpose:String(f.get('purpose')),distanceMiles:Number(f.get('distanceMiles')),startPostcode:String(f.get('startPostcode')||''),endPostcode:String(f.get('endPostcode')||''),source:'manual'};const r=await fetch('/api/provider/finance/mileage',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));setMessage(d.message||d.error||'Unable to record mileage.');setBusy(false);if(r.ok){event.currentTarget.reset();setTimeout(()=>window.location.reload(),700)}}
  return <form className='form-card' onSubmit={submit}><h2>Record business mileage</h2><div className='form-grid'><label>Date<input type='date' name='travelledOn' required/></label><label>Miles<input type='number' name='distanceMiles' min='0.1' step='0.1' required/></label><label>Start postcode<input name='startPostcode'/></label><label>End postcode<input name='endPostcode'/></label></div><label>Business purpose<input name='purpose' required/></label><button className='button' disabled={busy}>{busy?'Saving…':'Save mileage record'}</button>{message&&<p className='form-message'>{message}</p>}</form>;
}
