import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';

const createSchema=z.object({organisationId:z.string().uuid(),serviceKey:z.string().trim().max(120).nullable().optional(),minimumDistanceKm:z.number().min(0).max(500),maximumDistanceKm:z.number().positive().max(500).nullable().optional(),chargePence:z.number().int().min(0).max(500000),rejectBeyondBand:z.boolean().default(false)}).superRefine((v,ctx)=>{if(v.maximumDistanceKm!=null&&v.maximumDistanceKm<=v.minimumDistanceKm)ctx.addIssue({code:'custom',path:['maximumDistanceKm'],message:'Maximum distance must be greater than minimum.'})});

async function membership(){const db=await getUserSupabase();if(!db)return null;const {data:{user}}=await db.auth.getUser();return user?{db,user}:null}

export async function POST(request:Request){const auth=await membership();if(!auth)return NextResponse.json({error:'Sign in required.'},{status:401});const parsed=createSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the travel band.'},{status:400});const {db,user}=auth;const {data:member}=await db.from('organisation_members').select('role').eq('organisation_id',parsed.data.organisationId).eq('user_id',user.id).maybeSingle();if(!member||!['owner','admin','manager'].includes(member.role))return NextResponse.json({error:'Only a business manager can change travel rules.'},{status:403});const {data,error}=await db.from('provider_travel_bands').insert({organisation_id:parsed.data.organisationId,service_key:parsed.data.serviceKey||null,minimum_distance_meters:Math.round(parsed.data.minimumDistanceKm*1000),maximum_distance_meters:parsed.data.maximumDistanceKm==null?null:Math.round(parsed.data.maximumDistanceKm*1000),charge_pence:parsed.data.chargePence,reject_beyond_band:parsed.data.rejectBeyondBand,active:true}).select('id,service_key,minimum_distance_meters,maximum_distance_meters,charge_pence,reject_beyond_band').single();if(error)return NextResponse.json({error:'Unable to save travel band.',detail:error.message},{status:409});return NextResponse.json({band:data},{status:201})}

export async function DELETE(request:Request){const auth=await membership();if(!auth)return NextResponse.json({error:'Sign in required.'},{status:401});const url=new URL(request.url);const id=url.searchParams.get('id');const organisationId=url.searchParams.get('organisation');if(!id||!organisationId)return NextResponse.json({error:'Band and organisation are required.'},{status:400});const {db,user}=auth;const {data:member}=await db.from('organisation_members').select('role').eq('organisation_id',organisationId).eq('user_id',user.id).maybeSingle();if(!member||!['owner','admin','manager'].includes(member.role))return NextResponse.json({error:'Only a business manager can change travel rules.'},{status:403});const {error}=await db.from('provider_travel_bands').update({active:false}).eq('id',id).eq('organisation_id',organisationId);if(error)return NextResponse.json({error:'Unable to disable travel band.'},{status:500});return NextResponse.json({ok:true})}
