import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';

const schema=z.object({organisationId:z.string().uuid(),jobId:z.string().uuid().optional(),incurredOn:z.string().date(),category:z.string().trim().min(2).max(80),description:z.string().trim().min(2).max(500),supplierName:z.string().trim().max(160).optional(),netPence:z.coerce.number().int().min(0),vatPence:z.coerce.number().int().min(0).default(0),taxCode:z.string().trim().max(40).optional()});

export async function POST(request:Request){
  const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the expense details.'},{status:400});
  const supabase=await getUserSupabase();if(!supabase)return NextResponse.json({error:'Sign in required.'},{status:401});const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});
  const {data:membership}=await supabase.from('organisation_members').select('role').eq('organisation_id',parsed.data.organisationId).eq('user_id',user.id).maybeSingle();if(!membership)return NextResponse.json({error:'Business membership required.'},{status:403});
  try{const admin=getAdminSupabase();const gross=parsed.data.netPence+parsed.data.vatPence;const {data:expense,error}=await admin.from('provider_expenses').insert({organisation_id:parsed.data.organisationId,job_id:parsed.data.jobId??null,incurred_on:parsed.data.incurredOn,category:parsed.data.category,description:parsed.data.description,supplier_name:parsed.data.supplierName||null,net_pence:parsed.data.netPence,vat_pence:parsed.data.vatPence,gross_pence:gross,tax_code:parsed.data.taxCode||null,created_by:user.id}).select('id').single();if(error||!expense)return NextResponse.json({error:'Unable to record expense.',detail:error?.message},{status:500});const lines=[{accountCode:parsed.data.category.toLowerCase().includes('travel')?'travel_expense':parsed.data.category.toLowerCase().includes('material')?'materials_expense':'other_expense',direction:'debit',amountPence:parsed.data.netPence,jobId:parsed.data.jobId||null,organisationId:parsed.data.organisationId},{accountCode:'bank',direction:'credit',amountPence:gross,jobId:parsed.data.jobId||null,organisationId:parsed.data.organisationId}];if(parsed.data.vatPence>0)lines.splice(1,0,{accountCode:'vat_input',direction:'debit',amountPence:parsed.data.vatPence,jobId:parsed.data.jobId||null,organisationId:parsed.data.organisationId});await admin.rpc('post_finance_journal',{p_idempotency_key:`expense:${expense.id}`,p_source_type:'provider_expense',p_source_id:expense.id,p_currency:'GBP',p_lines:lines,p_metadata:{category:parsed.data.category,supplierName:parsed.data.supplierName||null,taxCode:parsed.data.taxCode||null}});return NextResponse.json({id:expense.id,message:'Expense recorded and posted to the finance journal.'},{status:201});}catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Unable to record expense.'},{status:500});}
}
