import { NextResponse } from 'next/server';
import { z } from 'zod';
import { getUserSupabase } from '@/lib/supabase/server';

const schema=z.object({startsAt:z.string().datetime(),endsAt:z.string().datetime(),reason:z.string().trim().max(300).optional()}).refine(v=>new Date(v.endsAt)>new Date(v.startsAt),{path:['endsAt'],message:'End must be after start.'});

async function context(engineerId:string){const db=await getUserSupabase();if(!db)return null;const {data:{user}}=await db.auth.getUser();if(!user)return null;const {data:engineer}=await db.from('engineers').select('id,user_id,organisation_id').eq('id',engineerId).maybeSingle();if(!engineer)return null;const {data:member}=await db.from('organisation_members').select('role').eq('organisation_id',engineer.organisation_id).eq('user_id',user.id).maybeSingle();const own=engineer.user_id===user.id;const manager=Boolean(member&&['owner','admin','manager','dispatcher'].includes(member.role));return{db,user,engineer,allowed:own||manager}}

export async function POST(request:Request,{params}:{params:Promise<{engineerId:string}>}){const {engineerId}=await params;const ctx=await context(engineerId);if(!ctx)return NextResponse.json({error:'Sign in required.'},{status:401});if(!ctx.allowed)return NextResponse.json({error:'Access denied.'},{status:403});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Please check the time-off dates.'},{status:400});const {data,error}=await ctx.db.from('engineer_time_off').insert({engineer_id:engineerId,starts_at:parsed.data.startsAt,ends_at:parsed.data.endsAt,reason:parsed.data.reason||null}).select('id,starts_at,ends_at,reason').single();if(error)return NextResponse.json({error:'Unable to save time off.',detail:error.message},{status:409});return NextResponse.json({timeOff:data},{status:201})}

export async function DELETE(request:Request,{params}:{params:Promise<{engineerId:string}>}){const {engineerId}=await params;const ctx=await context(engineerId);if(!ctx)return NextResponse.json({error:'Sign in required.'},{status:401});if(!ctx.allowed)return NextResponse.json({error:'Access denied.'},{status:403});const id=new URL(request.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Time-off id required.'},{status:400});const {error}=await ctx.db.from('engineer_time_off').delete().eq('id',id).eq('engineer_id',engineerId);if(error)return NextResponse.json({error:'Unable to remove time off.'},{status:500});return NextResponse.json({ok:true})}
