import { NextResponse } from 'next/server';
import { getAdminSupabase,SupabaseConfigurationError } from '@/lib/supabase/admin';
import { internalRequestAuthorised } from '@/lib/internal';
import { haversineMeters,routeEta,type Coordinate } from '@/lib/routing';

type Job={id:string;assigned_engineer_id:string|null;requested_start:string|null;requested_end:string|null;latitude:number|null;longitude:number|null;estimated_duration_minutes:number|null;postcode:string|null};

async function travel(a:Coordinate,b:Coordinate){const routed=await routeEta(a,b);return routed?{seconds:routed.durationSeconds,meters:routed.distanceMeters,source:routed.source}:{seconds:Math.round(haversineMeters(a,b)/8.33),meters:haversineMeters(a,b),source:'coarse-fallback'}}

export async function POST(request:Request){
 if(!internalRequestAuthorised(request))return NextResponse.json({error:'Unauthorised.'},{status:401});
 try{const body=await request.json().catch(()=>({}));const serviceDate=typeof body.serviceDate==='string'?body.serviceDate:new Date().toISOString().slice(0,10);const organisationId=typeof body.organisationId==='string'?body.organisationId:null;const admin=getAdminSupabase();let query=admin.from('jobs').select('id,assigned_engineer_id,requested_start,requested_end,latitude,longitude,estimated_duration_minutes,postcode,matched_provider_id').gte('requested_start',`${serviceDate}T00:00:00`).lt('requested_start',`${serviceDate}T23:59:59.999`).not('assigned_engineer_id','is',null).in('status',['accepted','scheduled']);if(organisationId){const {data:provider}=await admin.from('providers').select('id').eq('organisation_id',organisationId).maybeSingle();if(!provider)return NextResponse.json({error:'Provider not found.'},{status:404});query=query.eq('matched_provider_id',provider.id)}const {data,error}=await query;if(error)return NextResponse.json({error:'Unable to load scheduled jobs.'},{status:500});const jobs=(data||[]) as Job[];const grouped=new Map<string,Job[]>();for(const job of jobs){if(!job.assigned_engineer_id||job.latitude==null||job.longitude==null)continue;const list=grouped.get(job.assigned_engineer_id)||[];list.push(job);grouped.set(job.assigned_engineer_id,list)}const plans:Array<Record<string,unknown>>=[];let baselineSeconds=0,optimisedSeconds=0;
 for(const [engineerId,list] of grouped){const original=[...list].sort((a,b)=>String(a.requested_start).localeCompare(String(b.requested_start)));for(let i=1;i<original.length;i++){const a={latitude:Number(original[i-1].latitude),longitude:Number(original[i-1].longitude)},b={latitude:Number(original[i].latitude),longitude:Number(original[i].longitude)};baselineSeconds+=(await travel(a,b)).seconds}const remaining=[...original];const ordered:Job[]=[];if(remaining.length)ordered.push(remaining.shift()!);while(remaining.length){const last=ordered[ordered.length-1];const origin={latitude:Number(last.latitude),longitude:Number(last.longitude)};let bestIndex=0,bestSeconds=Infinity;for(let i=0;i<remaining.length;i++){const c=remaining[i];const r=await travel(origin,{latitude:Number(c.latitude),longitude:Number(c.longitude)});if(r.seconds<bestSeconds){bestSeconds=r.seconds;bestIndex=i}}optimisedSeconds+=Number.isFinite(bestSeconds)?bestSeconds:0;ordered.push(remaining.splice(bestIndex,1)[0])}plans.push({engineerId,originalJobOrder:original.map(j=>j.id),suggestedJobOrder:ordered.map(j=>j.id),jobCount:ordered.length})}
 const improvement=baselineSeconds>0?Math.max(0,(baselineSeconds-optimisedSeconds)/baselineSeconds):0;const {data:run}=await admin.from('schedule_optimisation_runs').insert({organisation_id:organisationId,service_date:serviceDate,status:'optimised',input_snapshot:{jobCount:jobs.length,engineerCount:grouped.size,baselineTravelSeconds:baselineSeconds},output_plan:{plans,optimisedTravelSeconds:optimisedSeconds,applyMode:'suggestion_only'},improvement_score:Number((improvement*100).toFixed(3))}).select('id').single();return NextResponse.json({runId:run?.id,serviceDate,jobs:jobs.length,engineers:grouped.size,baselineTravelSeconds:baselineSeconds,optimisedTravelSeconds:optimisedSeconds,estimatedImprovementPercent:Number((improvement*100).toFixed(1)),plans,note:'Optimisation is suggestion-only; it never silently changes a confirmed customer appointment.'});
 }catch(error){if(error instanceof SupabaseConfigurationError)return NextResponse.json({error:'Production database credentials are not configured.'},{status:503});return NextResponse.json({error:'Schedule optimisation failed.'},{status:500})}
}
